# REINVENT4 TOML input example for sampling

run_type = "sampling"
device = "cpu"  # set torch device e.g. "cpu"
json_out_config = "_sampling.json"  # write this TOML to JSON


[parameters]

# Mol2Mol: find molecules similar to the provided molecules
model_file = "models/reinvent/priors/mol2mol_medium_similarity.prior"
sample_strategy = "beamsearch"  # multinomial or beamsearch (deterministic)
temperature = 1.0 # temperature in multinomial sampling
tb_logdir = "tb_logs"  # name of the TensorBoard logging directory

num_smiles = 10  # number of SMILES to be sampled, 1 per input SMILES
unique_molecules = true  # if true remove all duplicatesd canonicalize smiles
randomize_smiles = true # if true shuffle atoms in SMILES randomly


smiles_file = ""
output_file = ""
